# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/addPat.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AddNewPat(object):
    def setupUi(self, AddNewPat):
        AddNewPat.setObjectName("AddNewPat")
        AddNewPat.resize(410, 593)
        font = QtGui.QFont()
        font.setPointSize(15)
        AddNewPat.setFont(font)
        self.centralwidget = QtWidgets.QWidget(AddNewPat)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.anrede = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.anrede.setFont(font)
        self.anrede.setObjectName("anrede")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.anrede)
        self.herrfrau = QtWidgets.QComboBox(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.herrfrau.setFont(font)
        self.herrfrau.setObjectName("herrfrau")
        self.herrfrau.addItem("")
        self.herrfrau.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.herrfrau)
        self.nam = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.nam.setFont(font)
        self.nam.setObjectName("nam")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.nam)
        self.name = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.name)
        self.vorn = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vorn.setFont(font)
        self.vorn.setObjectName("vorn")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.vorn)
        self.vorname = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.vorname.setFont(font)
        self.vorname.setObjectName("vorname")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.vorname)
        self.geb = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.geb.setFont(font)
        self.geb.setObjectName("geb")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.geb)
        self.gebdat = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gebdat.setFont(font)
        self.gebdat.setObjectName("gebdat")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.gebdat)
        self.stra_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stra_2.setFont(font)
        self.stra_2.setObjectName("stra_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.stra_2)
        self.stra = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.stra.setFont(font)
        self.stra.setObjectName("stra")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.stra)
        self.hsnr = QtWidgets.QLabel(self.centralwidget)
        self.hsnr.setObjectName("hsnr")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.hsnr)
        self.hausnummer = QtWidgets.QLineEdit(self.centralwidget)
        self.hausnummer.setObjectName("hausnummer")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hausnummer)
        self.plz_2 = QtWidgets.QLabel(self.centralwidget)
        self.plz_2.setObjectName("plz_2")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.plz_2)
        self.plz = QtWidgets.QLineEdit(self.centralwidget)
        self.plz.setObjectName("plz")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.plz)
        self.ort_2 = QtWidgets.QLabel(self.centralwidget)
        self.ort_2.setObjectName("ort_2")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.ort_2)
        self.ort = QtWidgets.QLineEdit(self.centralwidget)
        self.ort.setObjectName("ort")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.ort)
        self.tel = QtWidgets.QLabel(self.centralwidget)
        self.tel.setObjectName("tel")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.tel)
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setObjectName("save")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.save)
        self.quit = QtWidgets.QPushButton(self.centralwidget)
        self.quit.setObjectName("quit")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.quit)
        self.telef = QtWidgets.QLineEdit(self.centralwidget)
        self.telef.setObjectName("telef")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.telef)
        AddNewPat.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddNewPat)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 410, 28))
        self.menubar.setObjectName("menubar")
        AddNewPat.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddNewPat)
        self.statusbar.setObjectName("statusbar")
        AddNewPat.setStatusBar(self.statusbar)

        self.retranslateUi(AddNewPat)
        QtCore.QMetaObject.connectSlotsByName(AddNewPat)
        AddNewPat.setTabOrder(self.herrfrau, self.name)
        AddNewPat.setTabOrder(self.name, self.vorname)
        AddNewPat.setTabOrder(self.vorname, self.gebdat)
        AddNewPat.setTabOrder(self.gebdat, self.stra)
        AddNewPat.setTabOrder(self.stra, self.hausnummer)
        AddNewPat.setTabOrder(self.hausnummer, self.plz)
        AddNewPat.setTabOrder(self.plz, self.ort)
        AddNewPat.setTabOrder(self.ort, self.save)
        AddNewPat.setTabOrder(self.save, self.quit)

    def retranslateUi(self, AddNewPat):
        _translate = QtCore.QCoreApplication.translate
        AddNewPat.setWindowTitle(_translate("AddNewPat", "MainWindow"))
        self.anrede.setText(_translate("AddNewPat", "Anrede"))
        self.herrfrau.setItemText(0, _translate("AddNewPat", "Herr"))
        self.herrfrau.setItemText(1, _translate("AddNewPat", "Frau"))
        self.nam.setText(_translate("AddNewPat", "Name"))
        self.vorn.setText(_translate("AddNewPat", "Vorname"))
        self.geb.setText(_translate("AddNewPat", "Geburtsdatum"))
        self.stra_2.setText(_translate("AddNewPat", "Straße"))
        self.hsnr.setText(_translate("AddNewPat", "Hausnummer"))
        self.plz_2.setText(_translate("AddNewPat", "PLZ"))
        self.ort_2.setText(_translate("AddNewPat", "Ort"))
        self.tel.setText(_translate("AddNewPat", "Telefon"))
        self.save.setText(_translate("AddNewPat", "Speichern"))
        self.quit.setText(_translate("AddNewPat", "Abbrechen"))

